logging:
  level:
    root: ERROR

spring:
  config:
    import: optional:secrets.yml

  application:
    name: whitegold

  kiteconnect:
    uri: "https://kite.zerodha.com/connect/login?v=3&api_key=${kiteconnect.api-key}"
  
